name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workingDirectory: ./13-caching
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        
      - name: Install dependencies
        working-directory: ${{ env.workingDirectory }}
        run: npm ci

      - name: Testing
        working-directory: ${{ env.workingDirectory }}
        run: npm run test

      - name: Building
        working-directory: ${{ env.workingDirectory }}
        run: npm run build

      - name: Deploying to nonprod
        working-directory: ${{ env.workingDirectory }}
        run: |
          echo "Deploying to nonprod"