name: 14 - Working with Artifacts
on:
  workflow_dispatch:

env:
  build-artifactkey: app-${{ github.sha }}

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./14-artifacts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x

      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('14-artifacts/package-lock.json') }}
          path: 14-artifacts/node_modules

      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
        
      - name: Unit tests
        run: npm run test -- --coverage

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: 14-artifacts/coverage

      - name: Build code
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.build-artifactkey }}
          path: 14-artifacts/build
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test-build]
    
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.build-artifactkey }}
          path: build
      
      - name: Show folder structure
        run: ls -R
        